name: "Release: Publish"
run-name: "Release: ${{ github.event.head_commit.message }}"


on:
  release:
    types: [published]

jobs:
  PublishTo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          pip install --upgrade hatch
      - name: Export Built Files
        id: export-files
        run: |
          cd ${GITHUB_WORKSPACE}
          REF="$(cut -d'+' -f1 <<<"${GITHUB_REF##*/}")"
          hatch -v build
          echo "whl-path=${GITHUB_WORKSPACE}/dist/deadline_cloud_for_cinema_4d-${REF}-py3-none-any.whl" >> ${GITHUB_OUTPUT}
          echo "tgz-path=${GITHUB_WORKSPACE}/dist/deadline_cloud_for_cinema_4d-${REF}.tar.gz" >> ${GITHUB_OUTPUT}
          echo "plugin-path=${GITHUB_WORKSPACE}/deadline_cloud_extension/DeadlineCloud.pyp" >> ${GITHUB_OUTPUT}
      - name: Upload Release Asset
        id: upload-release-asset-windows
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{steps.export-files.outputs.whl-path}}
            ${{steps.export-files.outputs.tgz-path}}
            ${{steps.export-files.outputs.plugin-path}}

